version: '3.8'
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5173:5173
    expose:
      - 5173
    networks:
      - strapi_network

networks:
  strapi_network:
    driver: bridge